### ISSUE TITLE
How to setup locally add to README.md

### ISSUE THREAD

**Issue by rushikeshadhav** [geekymeeky/e-bureau#10]

**Comment by madihamallick** [comment]
@rushikeshadhav Go ahead

**Comment by rushikeshadhav** [comment]
Do we have to run npm install and npm start

**Comment by rushikeshadhav** [comment]
Installation steps
!. Fork 
2. Clone
3. Change directory
4. Create new branch
5. Set upstream command
6. Run npm install
7. Run npm start
8. Make changes
9. Stage your changes.
10. Commit
11. Push your code

**Comment by madihamallick** [comment]
> Do we have to run npm install and npm start

No use "npm run dev"

**Comment by madihamallick** [comment]
@rushikeshadhav Also from future don't create issues only Mentors and PA's can create issues. Text on discord and the mentors or I will create issue.

**Comment by shrinishant** [comment]
@madihamallick is this issue still open? I would love to work on this issue.

**Comment by madihamallick** [comment]
Go ahead @shrinishant

**Comment by shrinishant** [comment]
@madihamallick Do I need to be assigned the issue? Or, I could still be able to contribute to it like making Pr.

**Comment by madihamallick** [comment]
@shrinishant Assigned You
