### ISSUE TITLE
Adding issue templates

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#11]
Add issue template for bug_report, feature_request and proposal.

**Comment by Aniket-508** [comment]
Hey @madihamallick , can you please assign me this?

**Comment by madihamallick** [comment]
> Hey @madihamallick , can you please assign me this?

sure @Aniket-508 Go ahead!

**Comment by Aniket-508** [comment]
@madihamallick Can I do one small request? Please upgrade this issue label to level2 as it requires three templates that too tailored according to the repo mentors.
