### ISSUE TITLE
Creating a Landing Page

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#14]
Create a Landing Page that will show when the user has not logged in.

**Comment by shefali12-ab** [comment]
Hello ma'am, can I work on this issue?

**Comment by madihamallick** [comment]
Sure @shefali12-ab Go ahead!

**Comment by shefali12-ab** [comment]
@madihamallick ma'am I am having some doubts, is there any discord channel for discussion?

**Comment by madihamallick** [comment]
> @madihamallick ma'am I am having some doubts, is there any discord channel for discussion?

Yes. Are you SWOC participant?

**Comment by shefali12-ab** [comment]
Yes ma'am

**Comment by madihamallick** [comment]
> 

https://www.linkedin.com/in/madiha-mallick-4410a1207/
text me on Linkedin I'll guide you

**Comment by shefali12-ab** [comment]
> > 
> 
> https://www.linkedin.com/in/madiha-mallick-4410a1207/ text me on Linkedin I'll guide you

sure ma'am.

**Comment by madihamallick** [comment]
@shefali12-ab update?

**Comment by shrinishant** [comment]
@shefali12-ab are you still working on this issue? Otherwise I would love to take it forward

**Comment by shefali12-ab** [comment]
Yes I am working on this issue, right now I am busy with my academics but I
will surely complete it. Even after SWOC.

**Comment by madihamallick** [comment]
@shrinishant If you have anything else that you want to add to the project to make it better just text me on discord or Linkedin I will create issue then you can go ahead with it.

**Comment by shrinishant** [comment]
@madihamallick kk Ma'am, Thanks
