### ISSUE TITLE
Remove bad looking hover effects in home page

### ISSUE THREAD

**Issue by iswarmondal** [geekymeeky/e-bureau#22]
![image](https://user-images.githubusercontent.com/73457704/146701078-ece0f4c2-35ef-48b1-b4d7-b06eef64d4fe.png)

This hover effect looks bad on the homepage and it takes away the text visibility.
It can be easily done using some CSS properties.
I would suggest adding a call to action for each section other than making the entire section clickable.

**Comment by AbhinavXT** [comment]
@iswarmondal There is already an issue regarding the homepage UI #18. Post your ideas there. The issue also contains the guidelines regarding suggesting ideas and making design changes.

**Comment by AbhinavXT** [comment]
Also please read  #12

**Comment by iswarmondal** [comment]
Thanks for the guidance. I'll suggest my thought there in #18 . Thank you.

**Comment by madihamallick** [comment]
> Thanks for the guidance. I'll suggest my thought there in #18 . Thank you.

@iswarmondal Yes comment on #18 you'll get assigned.
