### ISSUE TITLE
Adding a nice description to the project 

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#24]

**Comment by madihamallick** [comment]
@iswarmondal you can on this now.

**Comment by iswarmondal** [comment]
Thanks.

**Comment by madihamallick** [comment]
@iswarmondal update?

**Comment by iswarmondal** [comment]
Hay I did a PR for updating the Readme file. And it's now merged.

**Comment by madihamallick** [comment]
> Hay I did a PR for updating the Readme file. And it's now merged.

Okay!
