### ISSUE TITLE
Update the .gitignore file and remove .env file

### ISSUE THREAD

**Issue by AbhinavXT** [geekymeeky/e-bureau#5]
Update the .gitignore file and remove .env file

**Comment by github4maninder** [comment]
Hi, i dont see .env file in the .gitignore anymore. 
these are the files in the .gitignore  as of now. 

# local env files
.env.local
.env.development.local
.env.test.local
.env.production.local.

thanks. if anything needs to be removed. let me know.

**Comment by AbhinavXT** [comment]
@github4maninder You need to remove the `.env` file from the repository not the `.gitignore` file.
You need to add it in the `.gitigonre` file, so git won't track changes for it, and commit it to GitHub.
This is because `.env` file generally contains private data which should not be committed to a public repository.

Here is the `.env` file-
![Firefox_Screenshot_2021-12-12T02-51-24 435Z](https://user-images.githubusercontent.com/56548922/145698445-6733f30e-dd72-4639-8ad1-c6f2e0563a6d.png)

**Comment by github4maninder** [comment]
ohh my bad, took the instructions way to seriously. thanks for the clarification 🥇 . updated the .gitignore file with the .env command. I don't have the vercel account. Kindly authorize this at your end.

**Comment by github4maninder** [comment]
thanks for the access @AbhinavXT.

**Comment by AbhinavXT** [comment]
@madihamallick #16

**Comment by github4maninder** [comment]
Thank for assigning the issue. i have updated the .gitIgnore file with the .env cmd and removed the .env file from the repo

i believe this can be merged with the Main branch.

**Comment by madihamallick** [comment]
Yes It will be merged.

**Comment by github4maninder** [comment]
Thank you @madihamallick and  @AbhinavXT . I'm glad that I could contribute!

**Comment by madihamallick** [comment]
> Thank you @madihamallick and @AbhinavXT . I'm glad that I could contribute!

Good Work✨
