### ISSUE TITLE
Improve UI of Dashboard 

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#57]

**Comment by sulogna2001** [comment]
Hey Can I work on this issue under GSSOC22

**Comment by madihamallick** [comment]
sure, go ahead @sulogna2001

**Comment by sulogna2001** [comment]
hey can I get the credentials for the backend setup

**Comment by madihamallick** [comment]
> hey can I get the credentials for the backend setup

sure give your mailId I am sending

**Comment by sulogna2001** [comment]
roysulogna2001@gmail.com

**Comment by madihamallick** [comment]
> [roysulogna2001@gmail.com](mailto:roysulogna2001@gmail.com)

Mailed you

**Comment by sulogna2001** [comment]
@madihamallick I started the server but its only showing home page other pages are not showing up

**Comment by madihamallick** [comment]
> @madihamallick I started the server but its only showing home page other pages are not showing up.Can you help me with that

Go to `\Dashboard`

**Comment by sulogna2001** [comment]
It's working thank you

**Comment by sulogna2001** [comment]
@madihamallick thank you  are these work points going to be added to the gssoc 23 score?
