### ISSUE TITLE
Adding Sign Up page

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#6]

**Comment by sanjanarp** [comment]
I would like to work on this issue.
I just have to implement the UI right? and not the backend?

**Comment by anugoyal998** [comment]
I would like to work on this issue.
I will implement both UI and backend.

**Comment by madihamallick** [comment]
> I would like to work on this issue. I will implement both UI and backend.

@anugoyal998 Go ahead.

**Comment by anugoyal998** [comment]
> > I would like to work on this issue. I will implement both UI and backend.
> 
> @anugoyal998 Go ahead.

can you briefly describe the UI part and the type of signup page you want like passwordless signup or password signup
and, do I also need to send email (if using email authentication) to users for verifying the email?

**Comment by madihamallick** [comment]
> > > I would like to work on this issue. I will implement both UI and backend.
> > 
> > 
> > @anugoyal998 Go ahead.
> 
> can you briefly describe the UI part and the type of signup page you want like passwordless signup or password signup and, do I also need to send email (if using email authentication) to users for verifying the email?

Password signup, If you use email authentication that will be great, it's upto you.

**Comment by anugoyal998** [comment]
@madihamallick I have made the PR for the signup page
