### ISSUE TITLE
Adding Login Page

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#7]

**Comment by sanjanarp** [comment]
I would like to work on this issue.
I just have to implement the UI right? and not the backend?

**Comment by madihamallick** [comment]
> I would like to work on this issue. I just have to implement the UI right? and not the backend?

Yes. Just the UI. Take your time make the PR after a week so that it is counted.

**Comment by anugoyal998** [comment]
I would like to work on this issue.
I can implement both UI and backend.
UI will be provided to me or have to create my own?

**Comment by madihamallick** [comment]
> I would like to work on this issue. I can implement both UI and backend. UI will be provided to me or have to create my own?

work on the sign up page as of now.

**Comment by anugoyal998** [comment]
> > I would like to work on this issue. I can implement both UI and backend. UI will be provided to me or have to create my own?
> 
> work on the sign up page as of now.

ok

**Comment by sanjanarp** [comment]
@madihamallick Could you briefly describe the kind of UI required? and the fields the user has to fill in (name, email, password) ?

**Comment by madihamallick** [comment]
> @madihamallick Could you briefly describe the kind of UI required? and the fields the user has to fill in (name, email, password) ?

Yes, name phone no,, email etc.

**Comment by madihamallick** [comment]
@sanjanarp any updates?
