### ISSUE TITLE
fix the UI

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#72]
![Capture](https://user-images.githubusercontent.com/70858557/157589913-82500109-073e-484e-b15c-b8419875aee9.PNG)

**Comment by rsinghcodes** [comment]
Can you send me the link of this page, where this issue happening?

How would you like to see the improved design, any idea? Please tell...

**Comment by madihamallick** [comment]
https://e-bureau.vercel.app/Dashboard

Make this card similar to above cards. Open the link you will get the error

**Comment by rsinghcodes** [comment]
I guess you want something like this? 👇🏻 

![image](https://user-images.githubusercontent.com/67682451/157916642-682da8bd-8ef7-4d5f-85bc-6b6292ad985f.png)

**Comment by madihamallick** [comment]
Yes this is okay

**Comment by rsinghcodes** [comment]
Please assign it to me under **GSSoC'22**. I would like to work.

Thanks!

**Comment by madihamallick** [comment]
Great Go ahead

**Comment by rsinghcodes** [comment]
> Great Go ahead

I have not been assigned yet under **GSSoC'22**?

**Comment by madihamallick** [comment]
Assigned
