### ISSUE TITLE
Make Input box UI better of General Diary, Missing Report, Crime Report pages

### ISSUE THREAD

**Issue by rsinghcodes** [geekymeeky/e-bureau#77]
**Is your feature request related to a problem? Please describe.**
Improve input box UI of of General Diary, Missing Report, Crime Report pages. Padding and margin is also not good.

**Describe the solution you'd like...**
I would design better input box with well designed UI.

Please assign it to me under **GSSoC'22**.

**Comment by madihamallick** [comment]
Go ahead @rsinghcodes
