### ISSUE TITLE
Will Love to Change The UI of ABOUT US page

### ISSUE THREAD

**Issue by Abh1shekSingh** [geekymeeky/e-bureau#78]
**Is your feature request related to a problem? Please describe.**
I will change the beautify the UI of About u page, as text is not aligned, also it is not matching with the Ui of original Home page. There is Inconsistency in UI. I want to Fix this.

**Comment by Abh1shekSingh** [comment]
@geekymeeky  Please assign this issue to me
I want to work on this issue

**Comment by madihamallick** [comment]
Go ahead @Abh1shekSingh
