### ISSUE TITLE
Search your record

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#8]
Updating search your record part to show the data searched in a proper manner.

**Comment by anugoyal998** [comment]
I would like to work on this issue.
I have to just sort the records array on the basis of the query (Crime, General Diary, Missing) selected by the user?

**Comment by geekymeeky** [comment]
> I would like to work on this issue. I have to just sort the records array on the basis of the query (Crime, General Diary, Missing) selected by the user?

Currently, its just showing the json response from the database. Kindly, make a decent ui to showcase it.

**Comment by anugoyal998** [comment]
> > I would like to work on this issue. I have to just sort the records array on the basis of the query (Crime, General Diary, Missing) selected by the user?
> 
> Currently, its just showing the json response from the database. Kindly, make a decent ui to showcase it.

Ok I will work on it :)

**Comment by madihamallick** [comment]
@anugoyal998 Go ahead

**Comment by madihamallick** [comment]
@anugoyal998 any updates?

**Comment by anugoyal998** [comment]
> @anugoyal998 any updates?

😶😶not good in UI/UX part
If you can provide the design I will implement it

**Comment by madihamallick** [comment]
> 

just make a simple grid form where you can display the data.

**Comment by shrinishant** [comment]
Hey @anugoyal998 , are you still working on it? Or, may I take on this issue and start working on it?

**Comment by anugoyal998** [comment]
> Hey @anugoyal998 , are you still working on it? Or, may I take on this issue and start working on it?
> 

@shrinishant you can take it, i'm not working on this :)

**Comment by shrinishant** [comment]
kk thnks
@anugoyal998  ma'am, could you please assign this to me, i would like to contribute in this task?

**Comment by madihamallick** [comment]
Go ahead @shrinishant
