### ISSUE TITLE
Updating Readme

### ISSUE THREAD

**Issue by madihamallick** [geekymeeky/e-bureau#9]

**Comment by sanjanarp** [comment]
I would like to work on this issue

**Comment by madihamallick** [comment]
@sanjanarp Go ahead.

**Comment by madihamallick** [comment]
@sanjanarp add the contributions part too and try to make a attractive README file. You can refer to this https://github.com/geekymeeky/chitchat/blob/master/README.md

**Comment by madihamallick** [comment]
@Aniket-508 Go ahead with contribution section part
